<?php if ($block->isModuleEnabled()): ?>
    <div class="custom-checkout-note">
        <?= $block->escapeHtml($block->getCustomNote()) ?>
    </div>
<?php endif; ?>




<style>
.custom-checkout-note:before {
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    font-size: 24px;
    line-height: 24px;
    color: #006400;
    content: '\e60e';
    font-family: 'luma-icons';
    margin: -12px 0 0;
    vertical-align: middle;
    display: inline-block;
    font-weight: normal;
    overflow: hidden;
    speak: none;
    left: 0;
    top: 22px;
    width: 45px;
    position: absolute;
    text-align: center;
}
.custom-checkout-note {
	margin: 0 0 10px;
	padding: 12px 20px 12px 25px;
	display: block;
	font-size: 1.4rem;
	background: #e5efe5;
	color: #006400;
	padding-left: 45px;
	position: relative;
}
</style>